[project]
name = "riot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.0.0",
    "nodriver>=0.48.1",
    "numpy>=2.2.0",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.11",
    "scipy>=1.15.0",
]
